sudo: required
language: python
services:
  - docker

# Disable depth (for ./autogen.sh --system to pass)
git:
  depth: 9999999

before_install:
  - docker --version
  - docker pull nirs/vdsm-centos

script:
  - docker run --rm=true -it -v `pwd`:/vdsm:rw nirs/vdsm-centos bash -c "cd /vdsm && ./autogen.sh --system && make; make check"
